all_restaurants = [
"A Noodle Story",
"Alliance Seafood",
"Anglo Indian ",
"Ar Er Soup",
"Balestier Road Hoover Rojak",
"Bar-Roque Grill",
"Beach Road Fish Head Bee Hoon",
"Bedok Chwee Kueh",
"Bismillah Biryani",
"Chai Chuan Tou Yang Rou Tang",
"Chef Kang's Noodle House",
"Chen's Mapo Tofu",
"Chey Sua Carrot Cake",
"Chuan Kee Boneless Braised Duck",
"Depot Road Zhen Shan Mei Claypot Laksa",
"Eminent Frog Porridge & Seafood",
"Famous Sungei Road Trishaw Laksa",
"Fresh Taste Big Prawn Noodle",
"Fu Ming Cooked Food ",
"Guan Kee Fried Kway Teow ",
"Hawker Chan Soya Sauce Chicken Rice & Noodle",
"Heng",
"Hjh Maimunah ",
"Hock Hai (Hong Lim) Curry Chicken Noodle ",
"Hong Heng Fried Sotong Prawn Mee",
"Hong Kee Beef Noodle",
"Hong Kong Yummy Soup",
"Hoo Kee Rice Dumpling",
"Indocafe - The White House ",
"J2 Famous Crispy Curry Puff",
"Ka Soh",
"Koh Brother Pig's Organ Soup (Tiong Bahru Market) New",
"Kok Sen",
"Lagnaa",
"Lao Fu Zi Fried Kway Teow ",
"Lian He Ben Ji Claypot Rice",
"Man Man",
"Muthu's Curry",
"Na Na Curry",
"New Lucky Claypot Rice",
"Outram Park Fried Kway Teow Mee",
"Shi Hui Yuan",
"Shirokane Tori-tama",
"Sik Bao Sin (Desmond's Creation)",
"Sin Huat Eating House",
"Sin Kee Famous Cantonese Chicken Rice",
"Song Fa Bak Kut Teh",
"Tai Wah Pork Noodle",
"The Blue Ginger",
"Tian Tian Hainanese Chicken Rice",
"Tiong Bahru Hainanese Boneless Chicken Rice",
"Tiong Bahru Yi Sheng Fried Hokkien Prawn Mee",
"To-Ricos Guo Shi",
"True Blue Cuisine",
"Whole Earth",
"Yhingthai Palace",
"Zaffron Kitchen",
"Zai Shun Curry Fish Head",
]

urls = File.open("./all_restaurant-urls", "w")
all_restaurants.map do |restaurant|
  urls.puts "https://guide.michelin.com/sg/en/singapore-region/singapore/restaurant/#{restaurant.downcase.gsub(' ', '-')}"
end
